### ISSUE TITLE
ember-chosen with ember data

### ISSUE THREAD

**Issue by Crabar** [ChrisHonniball/ember-chosen#3]
Is it possible to use ember-chosen with ember data?
I tried next:

```
    {{#ember-chosen
        multiple=true
        searchContains=true
        displaySelectedOptions=false
        optionValuePath="id"
        optionLabelPath="name"
        content=model
        placeholderTextMultiple='Start typing...'}}
    {{/ember-chosen}}
```

Where model:

```
import Ember from 'ember';

export default Ember.Route.extend({
    model() {
        return this.store.findAll('someObject');
    }
});
```

But have no records in ember-chosen and no errors/warnings in console.

**Comment by ChrisHonniball** [comment]
Let me look into this. I'm pretty sure I've done it in my projects. I'll post up a demo using ember-cli-mirage for you in the docs.

**Comment by ChrisHonniball** [comment]
Published a new release for your problem

**Comment by Crabar** [comment]
Great! Thank you very much. Will update and try in few hours.

**Comment by Crabar** [comment]
It still doesn't work for me although I have updated to version 0.0.20.
Ember inspector shows that data exists in store, but "select" part of ember-chosen still empty.

```
<select id="ember545" multiple="" style="width: 100%; display: none;" class="ember-view ember-chosen">  
<!---->
</select>
```

Also, I have next model:

```
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  vol: DS.attr('number'),
  description: DS.attr('string'),
  category: DS.attr('string')
});
```

**Comment by ChrisHonniball** [comment]
I've put an example in the docs using this method. Without seeing your application code I won't be able to diagnose what's going on. Is it a private project or public so I could look at it?

**Comment by Crabar** [comment]
Here it is: https://github.com/drinkit/ember-client . Ember-chosen used in "builder.hbs".
I'm newbie in EmberJS, so it is quite possible that problem in my project not yours =). And thank you, that you spend your time for my problem.

**Comment by ChrisHonniball** [comment]
Found the issue. If block content is used then the component doesn't generate any content passed in. This allows you to manually code in content if you'd like to. Used in the example:

> `{{ember-chosen}}` with block content that effects another select boxes grouping.

I'll come up with a better solution to this and document the changes. For now I've added the above pull request for you.

**Comment by ChrisHonniball** [comment]
> I'm newbie in EmberJS, so it is quite possible that problem in my project not yours =).

Your code looks fine to me! :+1: I remember when I was an ember newbie. Trust me you'll move fast, the ember community is great to be a part of.

> And thank you, that you spend your time for my problem.

No problem! When I can diagnose problems in other applications it makes me better _and_ it gives me use cases for my components and makes them better!

**Comment by Crabar** [comment]
Thanks for help. Now it works like a charm. Good luck! =)

**Comment by igorpreston** [comment]
@ChrisHonniball 
I faced the same problem, though it does not work:

```
{{ember-chosen
    content=tags
    optionLabelPath="name"
    optionValuePath="id"
    placeholder="Select tags for post"
    multiple=true
    value=selectedTags}}
```

Tags is controller property that is set in model hook on the route:

```
model: function() {
  let tags = this.store.findAll('tag');
  this.controllerFor('posts.new').set('tags', tags);
  return this.store.createRecord('post');
}
```

But even if I return tags as model for `posts.new` route, it still doesn't show in select box.
Tag model looks like this:

```
name: DS.attr('string')
```

Any advice on how to fix this problem? Thanks.

**Comment by ChrisHonniball** [comment]
What does your console output of tags look like?

Your `tags` controller variable may be getting set as the `promise` rather than the actual array of models.

Under the `{{ember-chosen}}` put:

`{{log "tags: " tags}}`

Let me know what it shows in the console.

**Comment by igorpreston** [comment]
@ChrisHonniball it shows this:

```
tags: <DS.PromiseArray:ember1033> { isPending=Descriptor,  isSettled=Descriptor,  isRejected=false,  more...}
```

Seems it is a promise array, but how should I handle this correctly?

**Comment by ChrisHonniball** [comment]
How I typically handle these type of queries like this is:

``` javascript
// Whatever route
model() {
  return this.store.createRecord('post');
},

afterModel() {
  // Doing this here will prevent the route from loading until after the promise is fulfilled.
  return this.store.findAll('tag');
},

setupController(controller, model) {
  controller.setProperties({
    model: model,
    tags: this.store.peekAll('tag')
  });
}
// ...
```

That _may_ or _may not_ help but that is how I handle it because of loading states.

If it's a public repo I _could_ take a look at it.

As long as the item you're passing in is an `array` then the lookups should work. If the item you're passing isn't an `array` then you'll have to figure out where the array of models that you want to reference is hiding. I used to run in to problems where the array I wanted was hidden in the content hash of the item that I expected (i.e. `someVar.content` rather than just `someVar`).

**Comment by igorpreston** [comment]
@ChrisHonniball Thank you very much! Your advice helped me and now ember-chosen displays the list. 

Can you please also suggest how should I get the tag record itself and not **id** in optionValuePath? Because I would need to pass tag record itself to the controller action to setup relationship between post and tag when persisting data to the api?

```
{{ember-chosen
    content=tags
    optionValuePath="id" <= get tag model record instead of tag id
}}
```

**Comment by ChrisHonniball** [comment]
Currently I don't have an option for making the selection the actual model when it's sent back into your application. I'd have to look into that as an option.

Currently if only one of the optionPaths are set it defaults to the other one. It may be as simple as not defaulting it to the other path. I will have to look into this in the next few days. I'll get back to you on that one. I've moved that work to #5.
