### ISSUE TITLE
Use of Ember instead of lodash

### ISSUE THREAD

**Issue by gentlefox** [ChrisHonniball/ember-chosen#6]
Curious why you are using lodash instead of in-built methods available in Ember. :interrobang: 

ie:

```
// line 146
groups = _.uniq(groupNames);
// could be:
groups = Ember.computed.uniq(groupNames);
```

The other use of lodash, while more efficient, barely warrants the inclusion of a whole library.

```
// line 372
var found = _.indexOf(optionValue);
// becomes:
var found = value.indexOf(optionValue);
```

Also "Unless Ember.EXTEND_PROTOTYPES.String is false these methods will also be added to the String.prototype as well.", meaning anything using "Ember.String" can use String. In this case I understand it is for greater compatibility for those not using EXTEND_PROTOTYPES.

**Comment by ChrisHonniball** [comment]
I see no problem with this. I'd like to get rid of the lodash dependency. Planned.

**Comment by ChrisHonniball** [comment]
:+1: Lodash dependency removed.

**Comment by gentlefox** [comment]
👍
