### ISSUE TITLE
Bug Firefox: value don't update always on change

### ISSUE THREAD

**Issue by danielladurner** [ChrisHonniball/ember-chosen#7]
Firefox dosn't update the value correctly if you change the selectbox.
If like in your example you go from the highest to the lowest value it works.
If you go from 1 to 2, the 1 works, the second label dosnt changes anything, and if switch to the 3 label, the value is 2  and not 3.

![unbenannt](https://cloud.githubusercontent.com/assets/13588558/9682350/32f723f4-5306-11e5-93cf-bf09b684b4c9.png)

**Comment by ChrisHonniball** [comment]
I'll take look as soon as I can. I'm planning a complete rewriting of how the value updates are processed. Rather than using the change event I'm going to use actions on the options.
